In [2]:
!pip install -r requirements.txt

Requirement already satisfied: pandas==2.2.3 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from -r requirements.txt (line 6)) (2.2.3)
Requirement already satisfied: numpy==2.2.2 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from -r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: scipy in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from -r requirements.txt (line 8)) (1.15.1)
Requirement already satisfied: matplotlib in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from -r requirements.txt (line 11)) (3.10.0)
Requirement already satisfied: seaborn in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from -r requirements.txt (line 12)) (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (24.2)
Requirement already satisfied: pillow>=8 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 11)) (3.2.1)
Requirement already satisfied: six>=1.5 in /Users/huongnguyen/BDA602/venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 6)) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip install --upgrade pip

In [4]:
import pandas as pd 
import numpy as np 
import scipy as sp

import matplotlib as plt

In [5]:
kidney_df = pd.read_csv("Kidney_Disease_Dataset.csv")

In [12]:
kidney_df.tail(10)

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
1649,1650,89,0,0,1,2,22.859626,1,12.654568,2.130131,...,8.344253,70.945313,0,0,1,2.002629,9.742499,4.646004,0,Confidential
1650,1651,32,0,0,1,3,35.253136,0,4.841773,1.037494,...,1.771158,65.378786,0,0,0,0.191474,2.812123,4.533731,1,Confidential
1651,1652,42,1,1,1,3,21.653960,0,8.735558,3.434101,...,2.524631,93.200328,0,0,0,3.738646,3.088596,1.684372,0,Confidential
1652,1653,20,0,0,1,3,20.378015,1,14.809062,7.459221,...,5.813276,63.415192,0,1,0,0.447521,0.448998,9.833712,1,Confidential
1653,1654,73,1,0,1,3,35.634449,0,8.929558,6.260773,...,4.135998,72.032441,0,0,0,2.816752,4.974069,3.448310,1,Confidential
1654,1655,90,0,0,1,2,39.677059,1,1.370151,4.157954,...,2.138976,81.102765,0,0,0,0.951836,9.547583,2.046212,0,Confidential
1655,1656,34,0,0,2,1,28.922015,0,3.372073,9.647525,...,7.911566,10.600428,0,1,0,3.604147,1.609847,0.324417,0,Confidential
1656,1657,84,0,0,2,3,21.951219,0,15.825955,7.349964,...,0.015531,69.633427,0,0,0,0.801955,5.768617,4.935108,0,Confidential
1657,1658,90,0,0,2,2,24.964149,0,12.967462,0.618614,...,3.432765,31.858023,0,0,0,0.560298,2.744519,0.322592,1,Confidential
1658,1659,34,1,1,0,0,19.253258,1,11.396510,7.446314,...,9.293499,82.314878,0,0,0,1.754852,0.186400,4.553608,1,Confidential

In [16]:
# Query by Diet Quality --> Higher than Average Diet Quality 

print(kidney_df["DietQuality"].min(), kidney_df["DietQuality"].mean(), kidney_df["DietQuality"].max())

# Retrieve all observations of patients with higher than average diet qualities 

high_avg_diet = kidney_df.loc[kidney_df["DietQuality"] > kidney_df['DietQuality'].mean(), :]

# Sorting by Diet Quality with Pandas 
high_avg_diet = high_avg_diet.sort_values(
    by = ["DietQuality", "BMI"], # Primary sort = DietQuality, Secondary Sort = BMI
    ascending = False
)

print(len(high_avg_diet))

0.0024066974290226 5.02854440376087 9.998926667050492
824

In [21]:
def extract_categorical(
    df,  
    exclude_vars, 
    include_dtypes = ["int"],
): 
    # Dataframe of Categorical features ONLY
    cat_df = df.select_dtypes(
        include = include_dtypes
    ).drop(
        columns = exclude_vars
    )

    # COerce all features in DataFrame to Panda Categorical Types
    cat_df = cat_df.astype(
        "category"
    )

    return cat_df

In [22]:
kidney_df

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,1,71,0,0,0,2,31.069414,1,5.128112,1.676220,...,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1,Confidential
1,2,34,0,0,1,3,29.692119,1,18.609552,8.377574,...,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1,Confidential
2,3,80,1,1,0,1,37.394822,1,11.882429,9.607401,...,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1,Confidential
3,4,40,0,2,0,1,31.329680,0,16.020165,0.408871,...,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1,Confidential
4,5,43,0,1,1,2,23.726311,0,7.944146,0.780319,...,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1,Confidential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1654,1655,90,0,0,1,2,39.677059,1,1.370151,4.157954,...,2.138976,81.102765,0,0,0,0.951836,9.547583,2.046212,0,Confidential
1655,1656,34,0,0,2,1,28.922015,0,3.372073,9.647525,...,7.911566,10.600428,0,1,0,3.604147,1.609847,0.324417,0,Confidential
1656,1657,84,0,0,2,3,21.951219,0,15.825955,7.349964,...,0.015531,69.633427,0,0,0,0.801955,5.768617,4.935108,0,Confidential
1657,1658,90,0,0,2,2,24.964149,0,12.967462,0.618614,...,3.432765,31.858023,0,0,0,0.560298,2.744519,0.322592,1,Confidential
1658,1659,34,1,1,0,0,19.253258,1,11.396510,7.446314,...,9.293499,82.314878,0,0,0,1.754852,0.186400,4.553608,1,Confidential

In [23]:
kidney_cat_df = extract_categorical(
    df = kidney_df,
    include_dtypes = ['int', 'object'],
    exclude_vars = [
        "PatientID", "Age", "DoctorInCharge"
    ]
)

kidney_cat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Gender                         1659 non-null   category
 1   Ethnicity                      1659 non-null   category
 2   SocioeconomicStatus            1659 non-null   category
 3   EducationLevel                 1659 non-null   category
 4   Smoking                        1659 non-null   category
 5   FamilyHistoryKidneyDisease     1659 non-null   category
 6   FamilyHistoryHypertension      1659 non-null   category
 7   FamilyHistoryDiabetes          1659 non-null   category
 8   PreviousAcuteKidneyInjury      1659 non-null   category
 9   UrinaryTractInfections         1659 non-null   category
 10  SystolicBP                     1659 non-null   category
 11  DiastolicBP                    1659 non-null   category
 12  ACEInhibitors                  1659 non-null   category
 13  Diuretics                      1659 non-null   category
 14  Statins                        1659 non-null   category
 15  AntidiabeticMedications        1659 non-null   category
 16  Edema                          1659 non-null   category
 17  HeavyMetalsExposure            1659 non-null   category
 18  OccupationalExposureChemicals  1659 non-null   category
 19  WaterQuality                   1659 non-null   category
 20  Diagnosis                      1659 non-null   category
dtypes: category(21)
memory usage: 41.9 KB